'use client';
import {ArrowRight,ClipboardList,Phone,PhoneMissed,PenLine,Check,ChevronRight} from 'lucide-react';
export function BusinessWorkflow({onManual,onSimulator}:{onManual:()=>void;onSimulator:(source:string)=>void}){
 return <section className="business-page section" id="system-demo"><div className="wrap"><div className="owner-heading"><p className="eyebrow">FOR HVAC BUSINESS OWNERS</p><span className="system-label">HVAC Inquiry Capture System</span><h1>Capture website and unanswered-call inquiries in one place.</h1><p>This demonstration shows how a furnace request can enter through a web form or after-hours call, be categorized, assigned and tracked through follow-up.</p></div><div className="source-cards">
 <article><span className="source-icon"><ClipboardList/></span><h2>Website Estimate Form</h2><p>Collect structured estimate and service requests from the company website.</p><a href="#estimate" className="text-link">Try the form <ChevronRight size={16}/></a></article>
 <article><span className="source-icon"><Phone/></span><h2>After-Hours Assistant</h2><p>Capture caller details and the reason for calling when the office is closed.</p><button className="text-link" onClick={()=>onSimulator('After-Hours AI')}>Explore a call <ChevronRight size={16}/></button></article>
 <article><span className="source-icon"><PhoneMissed/></span><h2>Missed-Call Recovery</h2><p>Create a callback task when a caller cannot reach the team.</p><button className="text-link" onClick={()=>onSimulator('Missed-Call Recovery')}>Try callback capture <ChevronRight size={16}/></button></article>
 <article><span className="source-icon"><PenLine/></span><h2>Manual Staff Entry</h2><p>Allow office staff to add phone, referral and walk-in inquiries.</p><button className="text-link" onClick={onManual}>Add a staff inquiry <ChevronRight size={16}/></button></article>
 </div><div className="workflow-panel"><div className="workflow-heading"><div><p className="eyebrow">FROM FIRST CONTACT TO FOLLOW-UP</p><h2>One connected inquiry workflow</h2></div><span>Illustrative workflow · no messages sent</span></div><ol className="workflow-steps">{['Inquiry arrives','Details captured','Request categorized','Record created','Staff alerted','Callback or booking tracked'].map((s,i)=><li key={s}><span>0{i+1}</span><strong>{s}</strong>{i<5&&<ArrowRight size={18}/>}</li>)}</ol><p className="workflow-note">The assistant supports office staff when calls go unanswered or arrive after hours. The team reviews requests, confirms availability, and handles callbacks or bookings. Staff alerts are simulated here.</p><div className="button-row"><button className="btn" onClick={()=>onSimulator('After-Hours AI')}>Simulate After-Hours Call <ArrowRight size={18}/></button><a className="btn outline" href="#tracker">View Lead Tracker</a><a className="text-link" href="#home">Return to Customer Website</a></div></div>
 <div className="scope-section"><div><p className="eyebrow">BEYOND THIS PREVIEW</p><h2>What a client implementation can include</h2><p>Configured around the company’s staff, service area, and existing systems.</p></div><ul>{['Intake and call-flow mapping','Customized assistant script and FAQs','After-hours and unanswered-call rules','Service-area and request-type routing','Human-transfer and escalation rules','Website-form and CRM connection','Staff notifications','Test-call scenarios','Staff handover and documentation','30 days of launch support and tuning'].map(s=><li key={s}><Check size={16}/>{s}</li>)}</ul></div><p className="scope-note">Calling software, phone numbers and CRM subscriptions are selected and paid for separately by the client. A real implementation requires client-approved privacy, call-recording, communication-consent and data-retention language for the applicable jurisdiction.</p></div></section>;
}
