'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Phone,Info,CheckCircle2,RotateCcw,MessageSquare} from 'lucide-react';
import {Choice,Urgency} from './controls';
import {scenarios,scenarioTranscript,createCallInquiry,type Lead} from '@/lib/inquiries';
export function CallSimulator({initialSource,onCreate,onOpen,ready,storageOk}:{initialSource:string;onCreate:(l:Lead)=>void;onOpen:(id:string)=>void;ready:boolean;storageOk:boolean}){
 const [scenarioId,setScenarioId]=useState('no-heat'),[source,setSource]=useState(initialSource),[step,setStep]=useState(0),[result,setResult]=useState<Lead|null>(null);
 const resultPanel=useRef<HTMLElement>(null);
 useEffect(()=>{if(result){resultPanel.current?.focus({preventScroll:true});resultPanel.current?.scrollIntoView({behavior:'smooth',block:'start'});}},[result]);
 const created=useRef(false),scenario=scenarios.find(s=>s.id===scenarioId)!,transcript=scenarioTranscript(scenarioId);
 function advance(all=false){if(created.current)return;const next=all?transcript.length:Math.min(step+2,transcript.length);setStep(next);if(next===transcript.length){created.current=true;const lead=createCallInquiry(scenarioId,source);onCreate(lead);setResult(lead);}}
 function reset(){created.current=false;setStep(0);setResult(null);}
 return <section className="simulation-page section" id="call-simulator"><div className="wrap"><a className="text-link back-link" href="#system-demo">← Business workflow</a><div className="simulation-heading"><div><p className="eyebrow">AFTER-HOURS & UNANSWERED-CALL BACKUP</p><h1>Walk through a caller’s next step.</h1><p>A scripted conversation, followed by a structured inquiry for the team.</p></div><span className="simulation-tag"><MessageSquare size={16}/>Visual simulation</span></div><div className="notice simulator-disclaimer"><Info size={19}/><span>This is a fictional call simulation. No call is being placed or recorded. The information shown below is fictional and is stored only in this browser.</span></div><div className="simulation-grid"><aside className="simulation-settings"><h2>Choose a scenario</h2><Choice id="call-scenario" label="Fictional scenario" options={scenarios.map(s=>`${s.label} — ${s.urgency}`)} value={`${scenario.label} — ${scenario.urgency}`} onChange={v=>setScenarioId(scenarios.find(s=>`${s.label} — ${s.urgency}`===v)!.id)} disabled={step>0}/><Choice id="capture-source" label="Capture route" options={['After-Hours AI','Missed-Call Recovery']} value={source} onChange={setSource} disabled={step>0}/><p className="route-explainer">{source==='Missed-Call Recovery'?'Illustrates a scripted intake after an unanswered call and the callback task it creates. No outbound callback or text is sent.':'Illustrates intake while the office is closed. The assistant collects details for human follow-up.'}</p><div className="caller-card"><span>Fictional caller</span><h3>{scenario.name}</h3><p>{scenario.city}</p><p>{scenario.phone}</p><Urgency value={scenario.urgency}/></div><p className="simulation-footnote">Use “Continue conversation” to advance the script. Completing it creates one inquiry. Starting again creates a separate inquiry.</p>{step===0?<button className="btn" disabled={!ready} onClick={()=>advance()}>Start Simulation <ArrowRight size={17}/></button>:!result?<><button className="btn" onClick={()=>advance()}>{step+2>=transcript.length?'Finish & Create Inquiry':'Continue Conversation'} <ArrowRight size={17}/></button><button className="quiet" onClick={()=>advance(true)}>Complete remaining steps</button></>:<button className="btn outline" onClick={reset}><RotateCcw size={16}/>Start Another Simulation</button>}</aside>
 <div className="conversation-panel"><div className="conversation-header"><span className="source-icon"><Phone size={21}/></span><div><h2>{source==='After-Hours AI'?'After-hours intake':'Missed-call recovery intake'}</h2><p>{step===0?'Ready to begin':result?'Conversation complete':`Step ${Math.ceil(step/2)} of 4`} · prewritten script</p></div></div><div className="conversation" aria-live="polite" aria-relevant="additions">{step===0?<div className="conversation-empty"><MessageSquare size={32}/><h3>See what the assistant captures.</h3><p>Name, callback number, location, request type, urgency, and preferred callback time.</p></div>:transcript.slice(0,step).map((t,i)=><div key={scenarioId+i} className={'chat-turn '+(t.role==='Caller'?'caller':'assistant')}><span>{t.role}</span><p>{t.text}</p></div>)}</div></div></div>
 {result&&<section ref={resultPanel} tabIndex={-1} className="call-result" aria-label="Call summary"><div className="result-heading"><CheckCircle2 size={27}/><div><p className="eyebrow">INQUIRY CREATED</p><h2>Captured and ready for review.</h2><p>{result.id}</p></div></div>{!storageOk&&<p className="notice">Browser storage is unavailable. This inquiry is kept in memory and will be lost on refresh.</p>}<p className="result-summary">{result.callSummary}</p><dl className="summary-grid">{[['Source',result.source],['Request type',result.requestType],['Urgency',result.urgency],['Customer',result.name],['Callback number',result.phone],['Location',result.city],['Customer type',result.customerType],['Best callback time',result.time],['Assigned team',result.assignedTeam],['Callback status',result.callbackStatus],['Created',new Date(result.createdAt).toLocaleString()],['Disclosure status',result.disclosureStatus]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="next-action"><strong>Recommended next action</strong><p>{result.nextAction}</p></div><p className="result-meta">Staff notification simulated. No message, booking, or dispatch was sent.</p><button className="btn" onClick={()=>onOpen(result.id)}>Open This Inquiry in Tracker <ArrowRight size={18}/></button></section>}
 </div></section>;
}
