'use client';
import {useState} from 'react';
import {ArrowRight,Info} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Choice} from './controls';
import {blankForm,validateHomeowner,createWebsiteInquiry,createManualInquiry,requestTypes,teams,type Lead} from '@/lib/inquiries';
export function IntakeForm({manual=false,ready=true,onCreate}:{manual?:boolean;ready?:boolean;onCreate:(lead:Lead)=>void}){
 const [form,setForm]=useState<Record<string,string>>({...blankForm(),urgency:'Standard',assignedTeam:'Office team',customerType:'Not specified',nextAction:''});
 const [consent,setConsent]=useState(false),[errors,setErrors]=useState<Record<string,string>>({});
 const prefix=manual?'manual-':'home-';
 function change(k:string,v:string){setForm(f=>({...f,[k]:v}));setErrors(e=>({...e,[k]:''}));}
 function submit(e:React.FormEvent){e.preventDefault();const errs=validateHomeowner(form,consent);setErrors(errs);if(Object.keys(errs).length){requestAnimationFrame(()=>document.getElementById(prefix+Object.keys(errs)[0])?.focus());return;}onCreate(manual?createManualInquiry(form):createWebsiteInquiry(form));setForm({...blankForm(),urgency:'Standard',assignedTeam:'Office team',customerType:'Not specified',nextAction:''});setConsent(false);}
 const complete=!!(form.name.trim()&&form.phone.trim()&&form.city.trim()&&form.requestType&&consent);
 return <form className="estimate-form intake-form" onSubmit={submit} noValidate><div className="form-top"><h3>{manual?'Add an inquiry':'Your home. Your next step.'}</h3><span>* Required fields</span></div><div className="form-warning"><Info size={17}/><p>EverWarm is fictional. Enter test information only; never use real personal or customer details.</p></div><div className="form-grid">{[['name','Full name','text','Alex Example'],['phone','Phone number','tel','416-555-0100'],['city','City or postal code','text','Toronto']].map(([id,label,type,placeholder])=><div className="field" key={id}><label htmlFor={prefix+id}>{label} <span>*</span></label><input id={prefix+id} type={type} value={form[id]} onChange={e=>change(id,e.target.value)} placeholder={placeholder} required maxLength={150} autoComplete="off" aria-invalid={!!errors[id]} aria-describedby={errors[id]?prefix+id+'-error':undefined}/>{errors[id]&&<p className="error" id={prefix+id+'-error'}>{errors[id]}</p>}</div>)}<Choice id={prefix+'requestType'} label="What help do you need?" required options={requestTypes} value={form.requestType} onChange={v=>change('requestType',v)} error={errors.requestType}/><div className="field full"><label htmlFor={prefix+'email'}>Email address <span className="optional">(optional)</span></label><input id={prefix+'email'} type="email" value={form.email} onChange={e=>change('email',e.target.value)} placeholder="alex@example.com" autoComplete="off" maxLength={150} aria-invalid={!!errors.email} aria-describedby={errors.email?prefix+'email-error':undefined}/>{errors.email&&<p className="error" id={prefix+'email-error'}>{errors.email}</p>}</div></div>
 <Accordion type="single" collapsible className="additional-details"><AccordionItem value="details"><AccordionTrigger className="additional-trigger">Additional details</AccordionTrigger><AccordionContent><div className="form-grid"><Choice id={prefix+'property'} label="Property type" options={['Not specified','Detached','Semi-detached','Townhouse','Condominium','Other']} value={form.property} onChange={v=>change('property',v)}/><Choice id={prefix+'age'} label="Approximate furnace age" options={['Under 10 years','10–15 years','Over 15 years','Not sure']} value={form.age} onChange={v=>change('age',v)}/><Choice id={prefix+'contact'} label="Preferred contact method" options={['Phone','Email','Text']} value={form.contact} onChange={v=>change('contact',v)}/><Choice id={prefix+'time'} label="Best time to contact" options={['Not specified','Morning','Afternoon','Evening']} value={form.time} onChange={v=>change('time',v)}/><div className="field full"><label htmlFor={prefix+'additionalNotes'}>Additional notes</label><textarea id={prefix+'additionalNotes'} rows={3} maxLength={3000} placeholder="Anything else you’d like the team to know…" value={form.additionalNotes} onChange={e=>change('additionalNotes',e.target.value)}/></div></div></AccordionContent></AccordionItem></Accordion>
 {manual&&<div className="manual-routing"><h3>Routing details</h3><div className="form-grid"><Choice id={prefix+'urgency'} label="Urgency" options={['Standard','Urgent']} value={form.urgency} onChange={v=>change('urgency',v)}/><Choice id={prefix+'team'} label="Assigned team" options={teams} value={form.assignedTeam} onChange={v=>change('assignedTeam',v)}/><Choice id={prefix+'customerType'} label="Customer type" options={['Not specified','New customer','Existing customer']} value={form.customerType} onChange={v=>change('customerType',v)}/><div className="field"><label htmlFor={prefix+'nextAction'}>Next action</label><input id={prefix+'nextAction'} value={form.nextAction} onChange={e=>change('nextAction',e.target.value)} maxLength={300} placeholder="Review entry and arrange a callback"/></div></div></div>}
 <div className="consent"><Checkbox id={prefix+'consent'} checked={consent} onCheckedChange={v=>{setConsent(v===true);setErrors(e=>({...e,consent:''}));}} aria-required="true"/><label htmlFor={prefix+'consent'}>I will only enter fictional test information.</label></div>{errors.consent&&<p className="error">{errors.consent}</p>}<button className="btn submit" type="submit" disabled={!ready||!complete}>{manual?'Create Inquiry':'Submit Estimate Request'} <ArrowRight size={18}/></button></form>;
}
