import type { ReactNode } from "react";
export function LegalContent({page, contactHref, contactDetails}: {page: "privacy" | "terms" | "accessibility"; contactHref: string; contactDetails: ReactNode}) {
  return <><p className="eyebrow">SERVICE CAPTURE CO.</p><h1>{page === "privacy" ? "Privacy" : page === "terms" ? "Terms of use" : "Accessibility"}</h1><div className="review-notice"><strong>Pre-launch draft · Professional review required</strong><p>This page must be reviewed and updated before public launch to reflect the actual business, service providers and operating practices. It does not guarantee compliance with any law or standard.</p></div>
  {page === "privacy" ? <>
    <h2>Information in a System Review request</h2><p>The contact form asks for your full name, business email, company name and the inquiry-handling problem you describe. Details such as your website, phone number, service region, inquiry volume and current software can be discussed during the System Review; they are not collected by this initial form. Your agreement to be contacted is included with the request. Please do not include customer records, passwords or sensitive personal information.</p>
    <h2>Why information is collected and used</h2><p>Once a submission service is connected, these details are used to assess whether the system fits your business, respond to your request and arrange the System Review. Contact consent for this request is not a subscription to marketing messages. The packaged preview has no connected submission service and does not transmit or save form entries.</p>
    <h2>Service providers</h2><p>A selected hosting provider may process technical connection information such as IP addresses and request logs. Once configured, the form, email, calendar or CRM providers may process request information to deliver those services. The actual providers, processing locations and applicable terms must be identified before launch. No analytics service is connected in this package. Do not activate analytics until the provider and consent approach have been reviewed.</p>
    <h2>Retention and deletion</h2><p>Request information should be retained only as long as needed to handle the inquiry and any agreed services, subject to applicable recordkeeping obligations. Before launch, Service Capture Co. must set and document a retention period, access controls, deletion procedure and any backup retention limits for the selected providers. This draft does not claim those procedures are already operating.</p>
    <h2>Access, correction and deletion requests</h2><p>Once business contact details are configured, use the contact method below to request access, correction or deletion of information you supplied. We may need to verify that the request concerns your information. Any limits required by applicable obligations should be explained when responding. Until a contact method and the form are connected, this preview cannot receive privacy requests.</p>
    <h2>The EverWarm demonstration</h2><p>EverWarm Home Comfort is fictional. Enter fictional information only. Its example inquiries are stored locally in your browser; when storage is unavailable, the demo uses temporary memory. It does not send real calls, messages, bookings or CRM actions. Use its reset control to restore fictional sample data, or clear the demo’s browser storage to remove all local records. Storage is specific to your browser and the site or file from which the demo is opened.</p>
  </> : page === "terms" ? <>
    <h2>Informational use</h2><p>This website describes Service Capture Co.’s workflow design and implementation services for independent residential HVAC companies. It is an invitation to discuss your needs, not an agreement to supply services. Final scope, software requirements, fees and responsibilities must be set out in a separate approved agreement.</p>
    <h2>No guarantee of business results</h2><p>Service Capture Co. organizes inquiries a business already receives. It does not sell leads or guarantee inquiry volume, bookings, revenue, response speed or other business results. The HVAC company remains responsible for service decisions, staffing and customer follow-up.</p>
    <h2>Demonstration limitations</h2><p>EverWarm Home Comfort is a fictional interactive concept, not a real client or case study. Use invented information only. Its scripted simulations do not place calls, diagnose equipment, quote approved live prices, promise technician availability, confirm dispatch or connect to a real CRM. Browser-local records may be reset or lost.</p>
    <h2>Third-party services</h2><p>Calling software, telephone numbers, CRM subscriptions and usage are selected and paid for separately by the client. Their availability, charges and use are governed by the respective providers’ terms. Proposed integrations depend on compatible systems, access, testing and approval.</p>
    <h2>Intellectual property</h2><p>Website copy, the Service Capture Co. identity and original demonstration materials are provided for evaluation of the services. Rights in third-party software and assets remain with their owners. The separate implementation agreement should specify the ownership and permitted use of work supplied to a client.</p>
    <h2>Limitations requiring professional review</h2><p>The site and fictional demonstration are provided for informational evaluation. To the extent permitted by applicable law, the final terms may limit responsibility for site interruptions, inaccuracies and losses arising from reliance on the demonstration. A qualified professional must review the scope, enforceability, exceptions and any liability limits before launch. Nothing here is intended to exclude rights or obligations that cannot lawfully be excluded.</p>
    <h2>Changes and agreements</h2><p>The site may be updated as services and selected software change. A signed client agreement, when applicable, governs the actual implementation. Any governing law, dispute process and other contractual provisions require professional review and are not assumed in this draft.</p>
  </> : <>
    <h2>Our approach</h2><p>Service Capture Co. aims to make information and the System Review request usable by people with different access needs. This website uses semantic headings, visible keyboard focus, labelled form fields, text explanations for errors, expandable questions and layouts that adapt to screen size. Motion is reduced when your device requests it.</p>
    <h2>Using the website</h2><p>Use Tab and Shift+Tab to move between links and controls, Enter to follow links, and Enter or Space to operate buttons and FAQ questions. The first keyboard link skips navigation. On small screens, the navigation button opens the menu; Escape closes the open menu. Browser zoom and text resizing are supported.</p>
    <h2>Demonstration and external services</h2><p>The EverWarm demonstration opens in a separate tab. It includes its own navigation and form controls. Accessibility of any future calendar, form provider or other external service needs to be assessed before connection. An accessible alternative should be available when a third-party workflow presents a barrier.</p>
    <h2>Feedback and assistance</h2><p>If you encounter a barrier, please describe the page, what you were trying to do, and the browser or assistive technology involved. Include only details you are comfortable sharing. Use the configured contact methods below, or the contact form once it is connected. This packaged preview cannot receive requests yet.</p>
    <h2>Ongoing review</h2><p>Accessibility checks have been included in development, but this statement does not claim certification or complete conformance with a standard. Before launch, review the completed site with assistive technology and confirm that connected services and contact alternatives are usable.</p>
  </>}
  <h2>Contact Service Capture Co.</h2>{contactDetails}<p><a href={contactHref}>Go to the contact section</a> to view available contact methods and the System Review form.</p></>;
}
