import type { ReactNode } from "react";
export const privacyEmail = "privacy@servicecaptureco.com";
export const privacyUpdated = "September 14, 2026";
export function LegalContent({page, contactHref, contactDetails}: {page: "privacy" | "terms" | "accessibility"; contactHref: string; contactDetails: ReactNode}) {
  return <><p className="eyebrow">SERVICE CAPTURE CO.</p><h1>{page === "privacy" ? "Privacy" : page === "terms" ? "Terms of use" : "Accessibility"}</h1>
  {page === "privacy"
    ? <div className="review-notice"><strong>Last updated {privacyUpdated}</strong><p>This policy describes how Service Capture Co. currently handles information. It is written in plain language, has not been reviewed by a lawyer, and does not claim compliance with any particular law.</p></div>
    : <div className="review-notice"><strong>Draft · Professional review pending</strong><p>This page has not yet been reviewed by a qualified professional. It does not guarantee compliance with any law or standard.</p></div>}
  {page === "privacy" ? <>
    <h2>Who we are</h2><p>Service Capture Co. designs and implements inquiry-handling workflows for independent HVAC companies. Questions about this policy or your information can be sent to <a href={`mailto:${privacyEmail}`}>{privacyEmail}</a>.</p>
    <h2>Information you send through the System Review form</h2><p>The form collects your full name, business email, company name and the inquiry-handling problem you describe, together with your agreement to be contacted and the wording of that agreement. The form also contains a hidden field used to detect automated spam; people normally leave it empty. Details such as your website, phone number, service region, inquiry volume and current software are discussed during the System Review, not collected by the form. Please do not include customer records, passwords or sensitive personal information.</p>
    <h2>How we use it</h2><p>We use these details to review your request, reply to you and arrange the System Review. Agreeing to be contacted about your request is not a subscription to marketing messages. We do not sell the information you send.</p>
    <h2>Service providers</h2><p>We rely on these providers to operate the website and handle your request:</p><ul><li><strong>Cloudflare</strong> hosts this website. It processes technical connection information, such as IP addresses, browser details and request logs, to deliver pages, protect the site from abuse and limit repeated form submissions.</li><li><strong>Resend</strong> delivers each form submission to our business mailbox as an email.</li><li><strong>Google Workspace</strong> provides our business email. Your request and any follow-up correspondence are stored in our mailbox there.</li></ul><p>These providers may process information outside Canada, including in the United States, under their own terms and privacy policies.</p>
    <h2>Cookies and analytics</h2><p>This website does not use analytics, advertising pixels or tracking cookies. Cloudflare may set strictly necessary security cookies to protect the site. The EverWarm demonstration stores its fictional records in your browser, as described below.</p>
    <h2>Retention and deletion</h2><p>We keep form requests and related email in our business mailbox until you ask us to delete them, or until we no longer need them to respond to your inquiry or provide services you have agreed to. Resend and Cloudflare keep their own delivery and security logs for limited periods under their own policies.</p>
    <h2>Access, correction and deletion requests</h2><p>To ask for a copy of the information you sent us, or to have it corrected or deleted, email <a href={`mailto:${privacyEmail}`}>{privacyEmail}</a>. We may need to confirm that the request concerns your own information.</p>
    <h2>The EverWarm demonstration</h2><p>EverWarm Home Comfort is fictional. Enter fictional information only. Its example inquiries are stored locally in your browser; when storage is unavailable, the demo uses temporary memory. It does not send real calls, messages, bookings or CRM actions, and nothing you enter in it is sent to us. Use its reset control to restore fictional sample data, or clear the demo’s browser storage to remove all local records.</p>
    <h2>Changes to this policy</h2><p>If our providers or practices change, we will update this page and the date above.</p>
  </> : page === "terms" ? <>
    <h2>Informational use</h2><p>This website describes Service Capture Co.’s workflow design and implementation services for independent residential HVAC companies. It is an invitation to discuss your needs, not an agreement to supply services. Final scope, software requirements, fees and responsibilities must be set out in a separate approved agreement.</p>
    <h2>No guarantee of business results</h2><p>Service Capture Co. organizes inquiries a business already receives. It does not sell leads or guarantee inquiry volume, bookings, revenue, response speed or other business results. The HVAC company remains responsible for service decisions, staffing and customer follow-up.</p>
    <h2>Demonstration limitations</h2><p>EverWarm Home Comfort is a fictional interactive concept, not a real client or case study. Use invented information only. Its scripted simulations do not place calls, diagnose equipment, quote approved live prices, promise technician availability, confirm dispatch or connect to a real CRM. Browser-local records may be reset or lost.</p>
    <h2>Third-party services</h2><p>Calling software, telephone numbers, CRM subscriptions and usage are selected and paid for separately by the client. Their availability, charges and use are governed by the respective providers’ terms. Proposed integrations depend on compatible systems, access, testing and approval.</p>
    <h2>Intellectual property</h2><p>Website copy, the Service Capture Co. identity and original demonstration materials are provided for evaluation of the services. Rights in third-party software and assets remain with their owners. The separate implementation agreement should specify the ownership and permitted use of work supplied to a client.</p>
    <h2>Limitations</h2><p>The site and fictional demonstration are provided for informational evaluation. To the extent permitted by applicable law, responsibility for site interruptions, inaccuracies and losses arising from reliance on the demonstration may be limited. A qualified professional has not yet reviewed the scope, enforceability or exceptions of these terms. Nothing here is intended to exclude rights or obligations that cannot lawfully be excluded.</p>
    <h2>Changes and agreements</h2><p>The site may be updated as services and selected software change. A signed client agreement, when applicable, governs the actual implementation. Governing law, dispute processes and other contractual provisions are set out in that agreement, not assumed here.</p>
  </> : <>
    <h2>Our approach</h2><p>Service Capture Co. aims to make information and the System Review request usable by people with different access needs. This website uses semantic headings, visible keyboard focus, labelled form fields, text explanations for errors, expandable questions and layouts that adapt to screen size. Motion is reduced when your device requests it.</p>
    <h2>Using the website</h2><p>Use Tab and Shift+Tab to move between links and controls, Enter to follow links, and Enter or Space to operate buttons and FAQ questions. The first keyboard link skips navigation. On small screens, the navigation button opens the menu; Escape closes the open menu. Browser zoom and text resizing are supported.</p>
    <h2>Demonstration and external services</h2><p>The EverWarm demonstration opens in a separate tab. It includes its own navigation and form controls. If a future calendar or other external service presents a barrier, an accessible alternative will be offered through the contact methods below.</p>
    <h2>Feedback and assistance</h2><p>If you encounter a barrier, please describe the page, what you were trying to do, and the browser or assistive technology involved. Include only details you are comfortable sharing. Use the contact methods below or the System Review form.</p>
    <h2>Ongoing review</h2><p>Accessibility checks were included in development, but this statement does not claim certification or complete conformance with a standard. Reports of barriers help us find and fix problems.</p>
  </>}
  <h2>Contact Service Capture Co.</h2>{contactDetails}<p><a href={contactHref}>Go to the contact section</a> to view available contact methods and the System Review form.</p></>;
}
