"use client";
import { useState, type ReactNode } from "react";
import { ArrowRight, ArrowUpRight, Check, CheckCheck, CircleCheck, ClipboardList, FileText, Globe, Inbox, Menu, MessageSquare, Phone, PhoneMissed, Route, ShieldCheck, Tag, X } from "lucide-react";
import { siteConfig } from "../../config/site";
import { safeWebUrl } from "./requests";
import { boundaries, demoFeatures, demoNotice, faqs, goodFit, homeServices, included, launchSupport, separateQuote, poorFit, problems, process, serviceComparison, serviceFaqs, services, stages } from "./content";
import { ReviewForm } from "./form";
import { LegalContent } from "./legal";
export type PageName = "home" | "services" | "interactive-demo" | "privacy" | "terms" | "accessibility" | "404";
export type SiteProps = {page?: PageName; offline?: boolean; openDemo?: () => void};
function Mark() {return <svg viewBox="0 0 40 40" aria-hidden="true" className="brand-mark"><rect width="40" height="40" rx="10" fill="currentColor"/><path d="M12 11H9v18h3M28 11h3v18h-3M14 20h12m-5-5 5 5-5 5" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/></svg>;}
function Brand({href}: {href: string}) {return <a className="brand" href={href} aria-label="Service Capture Co. home"><Mark/><span>Service Capture <span className="brand-co">Co.</span></span></a>;}
function Eyebrow({children}: {children: ReactNode}) {return <p className="eyebrow">{children}</p>;}
function Checklist({items, muted = false}: {items: string[]; muted?: boolean}) {return <ul className={`checklist ${muted ? "muted-list" : ""}`}>{items.map(item => <li key={item}>{muted ? <span aria-hidden="true" className="dash">—</span> : <Check size={17} aria-hidden="true"/>}<span>{item}</span></li>)}</ul>;}
function Workflow() {
  const rows = [
    {Icon: Inbox, title: "Website or phone inquiry", text: "An existing inquiry enters the workflow.", badge: "Incoming"},
    {Icon: ClipboardList, title: "Details captured", text: "Service · Location · Callback preference", badge: "Structured"},
    {Icon: Tag, title: "Request categorized", text: "Request type and urgency are recorded.", badge: "Organized"},
    {Icon: Route, title: "Team notified", text: "The approved team receives the next action.", badge: "Assigned"},
    {Icon: CheckCheck, title: "Follow-up tracked", text: "Callback status and notes stay together.", badge: "Visible"},
  ];
  return <div className="workflow-panel"><div className="panel-top"><span><span className="tiny-mark"/> INQUIRY WORKFLOW</span><span className="panel-label">Illustrative flow</span></div><ol className="workflow-list">{rows.map(({Icon,title,text,badge},i) => <li key={title}><span className={`flow-icon step-${i}`}><Icon size={21} strokeWidth={1.7}/></span><div><h3>{title}</h3><p>{text}</p></div><span className={`flow-badge badge-${i}`}>{badge}</span></li>)}</ol><div className="panel-bottom"><ShieldCheck size={16}/><span>Your team stays in control.</span><span className="flow-arrow">↗</span></div></div>;
}
export function SitePage({page = "home", offline = false, openDemo}: SiteProps) {
  const [menuOpen, setMenuOpen] = useState(false);
  const path = (slug = "", id = "") => offline ? `#/${slug}${id ? `?section=${id}` : ""}` : `/${slug}${slug ? "/" : ""}${id ? `#${id}` : ""}`;
  // The inquiry form stays the destination for "Request a System Review"; the booking page is a separate, external CTA.
  const review = path("", "contact");
  const booking = safeWebUrl(siteConfig.calendarUrl);
  const bookingLabel = "Book a 20-Minute Review";
  // One booking page serves every call to action; only the wording changes with the context.
  const bookingAria = (label: string) => `${label} (opens the Google Calendar booking page in a new tab)`;
  const bookCta = (label = bookingLabel, className = "primary") => booking ? <a className={`button ${className}`} href={booking} target="_blank" rel="noopener noreferrer" aria-label={bookingAria(label)}>{label}<ArrowUpRight size={18} aria-hidden="true"/></a> : null;
  const demoUrl = safeWebUrl(siteConfig.everWarmDemoUrl, true);
  const external = (href: string) => href.startsWith("https:") ? {target: "_blank", rel: "noopener noreferrer"} : {};
  const cta = (label = "Request a System Review", className = "primary") => <a className={`button ${className}`} href={review} {...external(review)}>{label}<ArrowUpRight size={18} aria-hidden="true"/></a>;
  const demoButton = (label = "Open the EverWarm Demo", className = "primary") => offline && openDemo ? <button className={`button ${className}`} onClick={openDemo}>{label}<ArrowUpRight size={18} aria-hidden="true"/></button> : demoUrl ? <a className={`button ${className}`} href={demoUrl} target="_blank" rel="noopener noreferrer">{label}<ArrowUpRight size={18} aria-hidden="true"/></a> : null;
  const nav = [["Services", path("services")], ["How It Works", path("", "how-it-works")], ["What We Build", path("", "what-we-build")], ["Interactive Demo", path("interactive-demo")], ["Pricing", path("", "pricing")], ["FAQ", path("", "faq")]];
  const contactDetails = <div className="contact-details">{siteConfig.businessEmail && <a href={`mailto:${siteConfig.businessEmail}`}>{siteConfig.businessEmail}</a>}{siteConfig.businessPhone && <a href={`tel:${siteConfig.businessPhone.replace(/[^+\d]/g, "")}`}>{siteConfig.businessPhone}</a>}{siteConfig.mailingAddress && <address>{siteConfig.mailingAddress}</address>}</div>;
  return <><a className="skip-link" href={offline ? path(page === "home" ? "" : page, "main-content") : "#main-content"}>Skip to content</a><header className="site-header"><div className="container header-inner"><Brand href={path()}/><button className="menu-toggle" aria-label={menuOpen ? "Close navigation" : "Open navigation"} aria-expanded={menuOpen} aria-controls="main-navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</button><nav id="main-navigation" aria-label="Main navigation" className={menuOpen ? "navigation is-open" : "navigation"} onKeyDown={event => {if (event.key === "Escape") {setMenuOpen(false); document.querySelector<HTMLButtonElement>(".menu-toggle")?.focus();}}}>{nav.map(([label,href]) => <a href={href} key={label} onClick={() => setMenuOpen(false)}>{label}</a>)}{booking ? <a className="header-cta" href={booking} target="_blank" rel="noopener noreferrer" aria-label={bookingAria(bookingLabel)} onClick={() => setMenuOpen(false)}>{bookingLabel} <ArrowUpRight size={15} aria-hidden="true"/></a> : <a className="header-cta" href={review} onClick={() => setMenuOpen(false)}>Request a Review <ArrowUpRight size={15}/></a>}</nav></div></header>
  <main id="main-content" tabIndex={-1}>
  {page === "home" ? <>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><Eyebrow>WEBSITES & INQUIRY SYSTEMS FOR HVAC COMPANIES</Eyebrow><h1>Websites and inquiry systems built for <span>independent HVAC companies.</span></h1><p className="hero-description">Service Capture Co. helps HVAC businesses improve how customers find them, request service and move through the inquiry process. Requests are captured, categorized, routed and organized so your team knows what needs attention next.</p><div className="hero-actions">{booking ? <>{bookCta()}<a className="text-link light" href={review}>Or send a System Review request <ArrowRight size={17}/></a></> : cta()}<a className="text-link light" href={path("interactive-demo")}>Explore the Interactive Demo <ArrowRight size={17}/></a></div><p className="channel-line">Website forms · After-hours calls · Missed-call recovery · Inquiry tracking</p></div><Workflow/></div><div className="hero-footer container"><span>Designed around the inquiries you already receive.</span><span>Built to support your existing team <ArrowDownIcon/></span></div></section>
    <section className="section problem-section"><div className="container"><div className="section-heading split-heading"><div><Eyebrow>BETWEEN FIRST CONTACT & FOLLOW-UP</Eyebrow><h2>The problem is often between the inquiry and the callback.</h2></div><p>An HVAC company can generate a valuable inquiry and still lose track of what happens next. Details may be incomplete, calls may arrive after hours, and follow-up responsibility may be unclear.</p></div><div className="four-grid problem-grid">{problems.map(([title,copy],i) => {const Icon = [PhoneMissed, FileText, Inbox, ClipboardList][i]; return <article className="problem-card" key={title}><Icon size={25} strokeWidth={1.6}/><h3>{title}</h3><p>{copy}</p></article>;})}</div></div></section>
    <section className="section ways-section" id="ways-we-can-help"><div className="container"><div className="section-heading split-heading"><div><Eyebrow>WAYS WE CAN HELP</Eyebrow><h2>Three ways to work together.</h2></div><p>Each one starts with the same 20-minute review. Full scope, inclusions and exclusions are on the Services page.</p></div><div className="three-grid ways-grid">{homeServices.map(([name, price, copy], i) => {const Icon = [Globe, Inbox, Route][i]; const target = services[[0, 2, 3][i]]; return <article className="way-card" key={name}><span className="way-icon"><Icon size={22} strokeWidth={1.7} aria-hidden="true"/></span><h3>{name}</h3><p className="way-price">{price}</p><p>{copy}</p>{i === 0 && <p className="way-note">Optional ongoing support: <strong>Website Growth &amp; Care, CAD $250 per month.</strong></p>}<a className="text-link" href={path("services", target.id)}>What’s included <ArrowRight size={16} aria-hidden="true"/></a></article>;})}</div><div className="ways-footer"><a className="button primary" href={path("services")}>Explore Services <ArrowRight size={18} aria-hidden="true"/></a><p>Not sure which fits? The review sorts that out in 20 minutes.</p></div></div></section>
    <section className="section system-section" id="what-we-build"><div className="container"><div className="section-heading"><Eyebrow>WHAT WE BUILD</Eyebrow><h2>One connected HVAC inquiry workflow.</h2><p>From first contact to a clear next action for your team.</p></div><div className="four-grid stages">{stages.map(([title,copy],i) => <article key={title}><div className="stage-top"><span>0{i + 1}</span>{i < 3 && <ArrowRight size={21}/>}</div><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="system-note"><Route size={20}/><p>The exact workflow depends on the company’s phone system, CRM, service area, staffing and approved escalation rules.</p></div><p className="small centered">Manual office entry can bring phone notes and staff-created requests into the same workflow.</p></div></section>
    <section className="section demo-section"><div className="container demo-grid"><div><Eyebrow>INTERACTIVE CONCEPT DEMO</Eyebrow><h2>See the workflow from the customer request to staff follow-up.</h2><p>{demoNotice}</p><Checklist items={demoFeatures}/><div className="demo-actions">{demoButton()}<a className="text-link" href={path("interactive-demo")}>See What the Demo Includes <ArrowRight size={16}/></a></div></div><div className="demo-card"><div className="demo-card-heading"><div className="everwarm-symbol">E<span>↗</span></div><div><strong>EverWarm</strong><span>HOME COMFORT</span></div><span className="concept-label">FICTIONAL DEMO</span></div><div className="demo-window"><div className="demo-window-title"><span>Explore the inquiry journey</span><span aria-hidden="true">↗</span></div><div className="demo-channel"><Globe size={20}/><div><strong>Customer-facing intake</strong><p>Website estimate form</p></div><ArrowRight size={18}/></div><div className="demo-channel"><Phone size={20}/><div><strong>Phone inquiry simulations</strong><p>After-hours & missed-call recovery</p></div><ArrowRight size={18}/></div><div className="demo-channel"><ClipboardList size={20}/><div><strong>Staff follow-up</strong><p>Unified inquiry tracker</p></div><ArrowRight size={18}/></div><div className="demo-footnote"><CircleCheck size={15}/> Browser-local, fictional information only</div></div><p className="demo-caption">A working concept you can explore. No live calls or CRM actions.</p></div></div></section>
    <section className="section pricing-section" id="pricing"><div className="container"><div className="price-box"><div className="price-intro"><Eyebrow>THE CORE OFFER</Eyebrow><h2>HVAC Inquiry Capture System</h2><p className="price"><span>CAD</span> $2,500</p><p className="price-label">One-time implementation</p>{booking ? bookCta("Book a System Review") : cta()}<p className="price-support">Built around your process.<br/>Tested and approved with your team.</p></div><div className="price-inclusions"><h3>What the CAD $2,500 implementation includes</h3><Checklist items={included}/><p className="cost-note">Third-party calling software, phone numbers, CRM subscriptions and usage charges are selected and paid for separately by the client.</p><p className="scope-compatibility">Integrations depend on compatibility, access, testing and client approval. Final scope is confirmed after the System Review.</p></div></div><div className="two-grid scope-details"><article className="fit-card"><h3>30 days of support and tuning</h3><p>After launch, we help your team settle into the delivered workflow.</p><Checklist items={launchSupport}/></article><article className="fit-card"><h3>When your needs go further</h3><p>The following require a separate quote:</p><Checklist items={separateQuote}/></article></div><p className="centered pricing-link"><a className="text-link" href={path("services")}>Compare all four services and prices <ArrowRight size={16} aria-hidden="true"/></a></p></div></section>
    <section className="section fit-section"><div className="container"><div className="section-heading"><Eyebrow>IS THIS THE RIGHT FIT?</Eyebrow><h2>Built for HVAC companies that already receive inquiries.</h2></div><div className="two-grid"><article className="fit-card"><h3><CircleCheck size={23}/> Strong fit</h3><Checklist items={goodFit}/></article><article className="fit-card muted"><h3><span aria-hidden="true">—</span> Probably not the right fit</h3><Checklist items={poorFit} muted/></article></div></div></section>
    <section className="section process-section" id="how-it-works"><div className="container"><div className="section-heading split-heading"><div><Eyebrow>HOW IT WORKS</Eyebrow><h2>A controlled path from first review to launch.</h2></div><p>Timing depends on access, software selection and client approvals. We confirm the schedule after the System Review.</p></div><div className="four-grid process-grid">{process.map(([title,copy],i) => <article key={title}><span className="process-number">0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="boundaries-section"><div className="container boundaries-grid"><div><ShieldCheck size={29}/><h2>Automation with human boundaries.</h2><p>Clear limits. Approved language.<br/>A person responsible for the next step.</p></div><Checklist items={boundaries}/></div></section>
    <section className="section faq-section" id="faq"><div className="container faq-grid"><div><Eyebrow>COMMON QUESTIONS</Eyebrow><h2>A clearer picture before we talk.</h2><p>What the system does, where it fits, and where people stay involved.</p><a className="text-link" href={path("", "contact")}>Have another question? <ArrowUpRight size={17}/></a></div><div className="faq-list">{faqs.map(([question,answer]) => <details key={question}><summary>{question}<span className="faq-plus" aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="section contact-section" id="contact"><div className="container contact-grid"><div className="contact-copy"><Eyebrow>LET’S MAP YOUR INQUIRY PROCESS</Eyebrow><h2>Request a 20-minute System Review.</h2><p>Tell us how your HVAC inquiries currently arrive. We’ll review the process and determine whether this system is appropriate for your company.</p><div className="review-outline"><span className="mini-icon"><MessageSquare size={22}/></span><div><h3>A focused first conversation</h3><p>How inquiries arrive.<br/>Where follow-up gets difficult.<br/>What a practical workflow could look like.</p></div></div>{booking && <div className="booking-cta"><p>Prefer to talk it through first? Book a 20-minute review, or send your details with the form.</p>{bookCta()}</div>}{contactDetails}<p className="contact-note">No lead-generation pitch. No promise of revenue.<br/>A practical review of your existing inquiry process.</p></div><ReviewForm offline={offline} privacyHref={path("privacy")}/></div></section>
  </> : page === "services" ? <>
    <section className="services-hero"><div className="container"><a className="back-link" href={path()}>← Back to Service Capture Co.</a><Eyebrow>SERVICES</Eyebrow><h1>Websites and inquiry systems built for <span>independent HVAC companies.</span></h1><p>Service Capture Co. helps HVAC businesses improve how customers find them, request service and move through the inquiry process. Four services, each with its own scope and price. The 20-minute review comes first, so you only start the one that fits.</p><div className="services-hero-actions">{booking ? bookCta() : cta()}<a className="text-link light" href={review}>Or send your details with the form <ArrowRight size={17} aria-hidden="true"/></a></div><p className="small">No lead generation. No promise of rankings, traffic or revenue.</p></div></section>
    <section className="section"><div className="container"><div className="services-stack">{services.map((service, i) => <article className="service-block" id={service.id} key={service.id}><div className="service-head"><div className="service-head-copy"><span className="service-index">0{i + 1}</span><h2>{service.name}{service.badge && <span className="service-badge">{service.badge}</span>}</h2><p className="service-summary">{service.summary}</p></div><div className="service-price-card"><p className="price-figure">{service.price}</p><p className="price-note">{service.priceNote}</p>{booking ? bookCta(service.cta) : cta(service.cta)}</div></div><div className="service-detail"><div><h3>What’s included</h3><Checklist items={service.includes}/></div><div><h3>Not included</h3><Checklist items={service.excludes} muted/><p className="small exclude-note">{service.excludesNote}</p></div><div><h3>Who it’s for</h3><Checklist items={service.who}/></div></div></article>)}</div></div></section>
    <section className="section compare-section"><div className="container"><div className="section-heading"><Eyebrow>SIMPLE COMPARISON</Eyebrow><h2>Which service fits your situation?</h2><p>Four rows, one decision. If none of them matches, the review will say so.</p></div><div className="compare-scroll"><table className="compare-table"><caption className="sr-only">Service Capture Co. services compared by price, situation and result</caption><thead><tr><th scope="col">Service</th><th scope="col">Price</th><th scope="col">Start here when</th><th scope="col">What you get</th></tr></thead><tbody>{serviceComparison.map(([name, price, when, result]) => <tr key={name}><th scope="row">{name}</th><td>{price}</td><td>{when}</td><td>{result}</td></tr>)}</tbody></table></div><p className="small compare-note">All prices are in Canadian dollars. Third-party software, phone, CRM, messaging and usage charges are selected and paid for separately by the client.</p></div></section>
    <section className="section faq-section"><div className="container faq-grid"><div><Eyebrow>SERVICE QUESTIONS</Eyebrow><h2>Before you choose.</h2><p>Scope, prices and the limits of each service.</p><a className="text-link" href={path("", "contact")}>Have another question? <ArrowUpRight size={17} aria-hidden="true"/></a></div><div className="faq-list">{serviceFaqs.map(([question, answer]) => <details key={question}><summary>{question}<span className="faq-plus" aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="section"><div className="container closing-cta"><div><h2>Still deciding which one fits?</h2><p>Bring your current setup to a 20-minute review. We’ll name the service that fits, or tell you none does.</p></div>{booking ? bookCta() : cta()}</div></section>
  </> : page === "interactive-demo" ? <><section className="demo-page-hero"><div className="container"><a className="back-link" href={path()}>← Back to Service Capture Co.</a><Eyebrow>INTERACTIVE CONCEPT DEMO</Eyebrow><h1>One inquiry.<br/><span>A clear path to follow-up.</span></h1><p>{demoNotice}</p>{demoButton()}<p className="small">Opens in a separate tab so you can return to this guide.</p></div></section><section className="section"><div className="container"><div className="section-heading"><Eyebrow>INSIDE EVERWARM HOME COMFORT</Eyebrow><h2>Explore both sides of the workflow.</h2><p>The homeowner experience and the staff view are part of the same fictional demonstration.</p></div><div className="two-grid demo-guide">{demoFeatures.map((title,i) => <article className="fit-card" key={title}><span className="process-number">0{i+1}</span><h3>{title}</h3><p>{["Enter an invented name and contact details in the homeowner estimate form. Follow the confirmation to see the captured inquiry.", "From the business workflow, choose Simulate After-Hours Call. Advance a scripted conversation and inspect its summary and follow-up task.", "Choose missed-call recovery in the business workflow. Complete a fictional scenario and see how the inquiry is categorized for human follow-up.", "Search and filter requests, open an inquiry, edit the next action and update its callback status. Manual office entry is available too."][i]}</p></article>)}</div><div className="demo-boundary"><ShieldCheck/><div><h3>A demonstration, with clear limits.</h3><p>EverWarm is not a real customer, case study or business result. Its example records stay in your browser. No real calls, messages, notifications, bookings, dispatch or CRM actions occur. Use Reset Demo Data in the tracker to restore the fictional examples. Clearing the demo’s browser storage removes your local records.</p></div></div><div className="closing-cta"><div><h2>What would this look like for your team?</h2><p>Start with your current inquiry process.</p></div>{booking ? bookCta() : cta()}</div></div></section></> : page === "404" ? <section className="section not-found container"><Eyebrow>404 · PAGE NOT FOUND</Eyebrow><h1>This request took a wrong turn.</h1><p>The page may have moved, or the address may be incomplete.</p><a href={path()} className="button primary">Return home <ArrowRight size={18}/></a></section> : <section className="section legal-page container"><a className="back-link" href={path()}>← Back to home</a><LegalContent page={page} contactHref={path("", "contact")} contactDetails={contactDetails}/></section>}
  </main><footer className="site-footer"><div className="container"><div className="footer-main"><div><Brand href={path()}/><p>Websites and inquiry systems<br/>for independent HVAC companies.</p></div><nav aria-label="Footer navigation">{[["Home",path()],["Services",path("services")],["How It Works",path("","how-it-works")],["Interactive Demo",path("interactive-demo")],["Pricing",path("","pricing")],["Privacy",path("privacy")],["Terms",path("terms")],["Accessibility",path("accessibility")],["Contact",path("","contact")]].map(([label,href]) => <a key={label} href={href}>{label}</a>)}</nav></div><div className="footer-bottom"><p>Service Capture Co. provides workflow design and implementation services. Third-party software and telecommunications services are supplied under their respective providers’ terms.</p><span>© {new Date().getFullYear()} Service Capture Co.</span></div></div></footer></>;
}
function ArrowDownIcon() {return <span aria-hidden="true">↓</span>;}
